# Original code from skyedeving and oldmud0
# at https://github.com/AttorneyOnline/AO2-Client/blob/master/.github/workflows/build.yml
name: build-mac

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  macos:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Setup workspace
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        echo "parentworkspace=/Users/runner/work/DRO-Client/" >> $GITHUB_ENV
        mkdir "3rd"
        mkdir "3rd/include"
        mkdir "3rd/x86_64"
        
    - name: Fetch Discord external library
      shell: bash
      working-directory: ${{env.parentworkspace}}
      run: |
        curl -L https://github.com/discordapp/discord-rpc/releases/download/v3.4.0/discord-rpc-osx.zip -o discord_rpc_osx.zip
        unzip discord_rpc_osx.zip
        cp ./discord-rpc/osx-dynamic/include/discord_register.h ./DRO-Client/3rd/include
        cp ./discord-rpc/osx-dynamic/include/discord_rpc.h ./DRO-Client/3rd/include
        cp ./discord-rpc/osx-dynamic/lib/libdiscord-rpc.dylib ./DRO-Client/3rd/x86_64
      
    - name: Fetch Bass external library
      shell: bash
      working-directory: ${{env.parentworkspace}}
      run: |
        curl http://www.un4seen.com/files/bass24-osx.zip -o bass.zip
        unzip bass.zip
        cp ./bass.h ./DRO-Client/3rd/include
        cp ./libbass.dylib ./DRO-Client/3rd/x86_64
        
    - name: Fetch QtApng external library
      shell: bash
      working-directory: ${{env.parentworkspace}}
      # ./clang_64/plugins/imageformats/libqapng.dylib
      run: |
        curl -L https://github.com/Skycoder42/QtApng/releases/download/1.1.4/qtapng-clang_64-5.14.1.tar.xz -o qtapng.tar.xz
        tar -xvf qtapng.tar.xz
        ls -R
        
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-qt5

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        cached: ${{steps.cache-qt.outputs.cache-hit}}
